name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: |
        go test -race ./... && go vet ./...

    - name: Build
      run: CGO_ENABLED=0 go build -v .

    - name: Deploy - Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Deploy - Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      id: upload-release-asset 
      uses: csexton/release-asset-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-url: ${{ steps.create_release.outputs.upload_url }}
        files: |
          ayano